apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ''
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ''
    spec:
      containers:
        - name: ''
          image: ''
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: unnamed-service
  labels:
    name: unnamed-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ''
  type: ClusterIP
